// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlFtLk4jAicjpAij5z4b0rWA_stBV-6yM',
    appId: '1:201158383608:web:e4aafd54a2584a38f2680d',
    messagingSenderId: '201158383608',
    projectId: 'auth-ca669',
    authDomain: 'auth-ca669.firebaseapp.com',
    storageBucket: 'auth-ca669.firebasestorage.app',
    measurementId: 'G-B4XRGDWY4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqThVbiikL7iVjUC68DP3wr5b9fkeCf0c',
    appId: '1:201158383608:android:0782e2c060ef6646f2680d',
    messagingSenderId: '201158383608',
    projectId: 'auth-ca669',
    storageBucket: 'auth-ca669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkExAIgEMefk1xT3hbwu15Z6PT-wlvDf0',
    appId: '1:201158383608:ios:c329aa72ba99cce3f2680d',
    messagingSenderId: '201158383608',
    projectId: 'auth-ca669',
    storageBucket: 'auth-ca669.firebasestorage.app',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkExAIgEMefk1xT3hbwu15Z6PT-wlvDf0',
    appId: '1:201158383608:ios:c329aa72ba99cce3f2680d',
    messagingSenderId: '201158383608',
    projectId: 'auth-ca669',
    storageBucket: 'auth-ca669.firebasestorage.app',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlFtLk4jAicjpAij5z4b0rWA_stBV-6yM',
    appId: '1:201158383608:web:e84fe10fcbdcacdff2680d',
    messagingSenderId: '201158383608',
    projectId: 'auth-ca669',
    authDomain: 'auth-ca669.firebaseapp.com',
    storageBucket: 'auth-ca669.firebasestorage.app',
    measurementId: 'G-TJ8MZKNNXE',
  );
}
